### ISSUE TITLE
pod 适配Swift5后 运行报错！~急

### ISSUE THREAD

**Issue by doomc** [HHMedic/HHDoctorSDK_demo_iOS#1]
<img width="441" alt="屏幕快照 2019-04-23 下午1 34 36" src="https://user-images.githubusercontent.com/11433748/56557310-1ebe4d80-65cd-11e9-9034-dea51d6ef2c5.png">

**Comment by ashen-23** [comment]
已适配

**Comment by HHMedic** [comment]
已适配Swift5
